### ISSUE TITLE
XYChart issues with long x-axis labels

### ISSUE THREAD

**Issue by mlilienberg** [KoalaPlot/koalaplot-core#11]
First thanks a lot for this great library. 
I am struggling a bit to show a VerticalBarChart with long labels on the x-axis. Spread sheet applications like Excel or Google Sheets offer to show the labels in an rotated angle so that the labels do not overlap. It would be a quite nice enhancement for this library as well. I tried to achieve this on my own without changing the source code of this library but failed. While i was able to rotate and position the labels correctly, i did not achieve change the inner dimensions of the Text composable itself, so that the text wraps even there would be enough space to render the labels without soft wrap.
This screenshot shows how my intended chart is shown in google sheets.
<img width="551" alt="Screenshot 2023-04-23 at 17 42 29" src="https://user-images.githubusercontent.com/6872282/233850049-3d59c0bf-e3c1-4036-800a-73652df194d1.png">

**Comment by gsteckman** [comment]
If you used Modifier.rotate to rotate the composable with the text, I believe there is a bug affecting the measurements of the resulting rotated element - see https://stackoverflow.com/questions/70057396/how-to-show-vertical-text-with-proper-size-layout-in-jetpack-compose.

There is a suggested fix on that stackoverflow topic and I implemented it in [io.github.koalaplot.core.util](https://github.com/KoalaPlot/koalaplot-core/blob/main/src/commonMain/kotlin/io/github/koalaplot/core/util/Util.kt) as Modifier.rotateVertically. However, it only supports 90-degree rotations and not arbitrary angles.

I'd be interested to hear if that solves your problem, at least for 90-degree rotated labels on the x-axis. If so I can look at making that Modifier support all rotation angles, or if you'd like to give it a try I'd be happy to accept a contribution.

**Comment by gsteckman** [comment]
Thinking about this more, it's a bit more complex because when you rotate something, its dimensions will still be returned by Compose in the original (screen) axis coordinates, not in the rotated coordinate system of the item. The current implementation should work ok with 0-degree and 90-degree rotations, but not with arbitrary rotation angles. That's going to take some work to figure out how to do with Compose.

**Comment by gsteckman** [comment]
Added support for rotating axis labels. See the sample for [Stacked Vertical Bar chart](https://github.com/KoalaPlot/koalaplot-samples/blob/main/src/commonMain/kotlin/io/github/koalaplot/sample/StackedVerticalBarSample.kt).

![image](https://github.com/KoalaPlot/koalaplot-core/assets/27028452/c41734af-8eda-4967-a6d2-4d384239517d)
