### ISSUE TITLE
Add KoalaPlot to the list of libraries in https://github.com/AAkira/Kotlin-Multiplatform-Libraries

### ISSUE THREAD

**Issue by Ic-ks** [KoalaPlot/koalaplot-core#13]
The GitHub repository https://github.com/AAkira/Kotlin-Multiplatform-Libraries provides an overview of kotlin multiplatform libraries. I think KoalaPlot should be part of it :)

**Comment by gsteckman** [comment]
Submitted [PR #150](https://github.com/AAkira/Kotlin-Multiplatform-Libraries/pull/150)
