### ISSUE TITLE
Stairs for XYChart

### ISSUE THREAD

**Issue by mincequi** [KoalaPlot/koalaplot-core#14]
Hi there,
I stumbled across your lib when searching for a plot lib for Compose Multiplatform.
There is one question that arises: is there any chance to plot stairs for XY values?

Thanks in advance.

**Comment by gsteckman** [comment]
I'm not sure what you mean. Can you point to any examples?

**Comment by gsteckman** [comment]
Hi, this wasn't possible, but also not hard to add, so I added a StairstepChart Composable in the latest commit.
