### ISSUE TITLE
Consider publishing to maven central (already) for better adoption!

### ISSUE THREAD

**Issue by zoltish** [KoalaPlot/koalaplot-core#2]
This looks like an awesome library with a ton of potential! 

Im fairly certain that more people will play around with it if its easily accessible through maven central. Please consider publishing it even though the library is in its early stages.

**Comment by gsteckman** [comment]
Thanks for your feedback. 0.1.0 published to Maven Central!

**Comment by joreilly** [comment]
Hi, looks like typo in `README`

```
implementation("io.github.koalaplot:core:0.1.0")
```

should be?

```
implementation("io.github.koalaplot:koalaplot-core:0.1.0")
```

**Comment by gsteckman** [comment]
Yes, good catch!
