### ISSUE TITLE
Feature Request: Allow disabling of all input (Bar Chart)

### ISSUE THREAD

**Issue by Wavesonics** [KoalaPlot/koalaplot-core#21]
My charts are in a scrollable column, and currently, they swallow all input events even with `enabled = false`.

This means I can't scroll my column when my finger is passing over the chat. it makes for some very awkward scrolling.

So far this is happening for me with BarChart, but not PieChart.

**Comment by gsteckman** [comment]
The XYChart can be zoomed and panned, while the PieChart cannot. This was interfering with scrolling since it captures drag events for panning. I added an option to XYChart to disable the pan/zoom capability, which should eliminate the interference with scrolling the parent.

**Comment by gsteckman** [comment]
Implemented in b430c1f43eabb27c1f401ba250ee8c142725c29c
