### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by joreilly** [KoalaPlot/koalaplot-core#30]
Hi, is there plan to support Wasm target?

**Comment by gsteckman** [comment]
Yes, I am interested in this. I was waiting for it to mature a bit and I saw the announcement that it is now Alpha, so it's probably time.

**Comment by gsteckman** [comment]
I released 0.5.0 with wasm support. The [web samples](https://koalaplot.github.io/koalaplot-samples/wasmJs/productionExecutable/index.html) are now using wasm.
