### ISSUE TITLE
Can't find a lot of new classes

### ISSUE THREAD

**Issue by joshafeinberg** [KoalaPlot/koalaplot-core#31]
I'm seeing a bunch of `ReplaceWith` though the class it wants me to change to doesn't seem to exist

Example:
https://github.com/KoalaPlot/koalaplot-core/blob/1fc11c36bca9758d7173fff003f296b5a981a286/src/commonMain/kotlin/io/github/koalaplot/core/bar/VerticalBarChart.kt#L41

However if I search the codebase for `BarPlotEntry` (https://github.com/search?q=repo%3AKoalaPlot%2Fkoalaplot-core%20BarPlotEntry&type=code) it doesn't exist. There is `VerticalBarPlotEntry` which seems to the right one?

Theres a lot of these such as `FloatStackedAreaPlotEntry` (https://github.com/KoalaPlot/koalaplot-core/blob/1fc11c36bca9758d7173fff003f296b5a981a286/src/commonMain/kotlin/io/github/koalaplot/core/line/LineChart.kt#L573)  [Search Results](https://github.com/search?q=repo%3AKoalaPlot%2Fkoalaplot-core%20FloatStackedAreaPlotEntry&type=code) so i'm not sure if there are just some missing commits or what is happening here

There is also no implementation of `StackedAreaPlotEntry`, Float or otherwise

**Comment by gsteckman** [comment]
In the first case, use VerticalBarPlotEntry as you suspected. The second comment I need to remove - it was a path I was going down during development but didn't get into this release. StackedAreaPlotDataAdapter might be of interest if your data is in lists of floats. I'll scan the @Deprecated annotations for other errors and issue an updated release.

**Comment by gsteckman** [comment]
Release 0.5.1 fixes these and a few more I found. Please open a new issue if you find any more.
