### ISSUE TITLE
Plot area shrinks when x axis labels are too long

### ISSUE THREAD

**Issue by mikolajefento** [KoalaPlot/koalaplot-core#32]
When I do not provide any labels to x axis it fills up the space correctly. But when I try to add some long labels (for example dates) it seems to shrink the plot area and it does no fill the space fully anymore. I post pictures of that behavior 
![image](https://github.com/KoalaPlot/koalaplot-core/assets/129855022/36cf2f67-7d20-4efc-8b68-078465b2e0a2)

**Comment by gsteckman** [comment]
This is the intended behavior. The tick labels are centered on the tick above them. To do that, some of the label needs to extend to the right of the right edge of the graph area. Therefore, the right edge of the graph area cannot be against the right edge of the parent container, or there would be no space for the right half of the label (it would be clipped). The same logic is used for the top of the graph and the highest y-axis label.

One option is to rotate the x-axis labels so they don't need so much horizontal space. That would also avoid the wrapping that you are seeing. The graph height will decrease to accommodate the height of the x-axis labels.

**Comment by mikolajefento** [comment]
Unerstood. Thanks for the sugestion, will definetly try that  🙌
