### ISSUE TITLE
Provide draw percentage like on the picture for pie chart

### ISSUE THREAD

**Issue by Monabr** [KoalaPlot/koalaplot-core#33]
Hello!

You have a great library!

Could you please provide pie chart percentage draw like on image?
![image](https://github.com/KoalaPlot/koalaplot-core/assets/30532666/0e3c59ac-2031-44b6-a21b-be9e417abb51)

**Comment by gsteckman** [comment]
I've thought about it before - to make it general purpose, I would implement a pie slice that can place a composable within it, centered on a caller-specified radial distance from the center of the pie and at an angular position midway through the slice.

One complication is that the provided Composable should be prepared to handle the situation where the available space is not big enough to be useful, e.g., when the slice is very narrow. I'm open to approaches for handling this within the pie chart itself, but am not sure how that can be done.
