### ISSUE TITLE
Build issue after update to Compose Multiplatform 1.6.0

### ISSUE THREAD

**Issue by joreilly** [KoalaPlot/koalaplot-core#44]
Hi, it looks like version `0.5.2` is built with Compose Multiplatform `1.6.0-beta01` which causes following issue when updating to `1.6.0`

https://github.com/JetBrains/compose-multiplatform/issues/4277

**Comment by Deorigami** [comment]
is there any fix for this @joreilly ?

**Comment by Deorigami** [comment]
is there any date for this library to be updated ?

**Comment by joreilly** [comment]
You'll need to ask library author about that :)

**Comment by Deorigami** [comment]
i thought that you were the author :D

**Comment by gsteckman** [comment]
Released 0.5.3 that uses Compose 1.6.0.
