### ISSUE TITLE
Support Scroll Axis

### ISSUE THREAD

**Issue by zaycode** [KoalaPlot/koalaplot-core#5]
I have tried several chart libraries on android but I didn't find the horizontal scroll axis feature like in the video, really appreciate if there is such a feature in this library

https://user-images.githubusercontent.com/5361004/197753088-59b51beb-0326-4ea9-874c-bcbbd32e9ecb.MP4

**Comment by Feinate** [comment]
Did you find a solution to it ?

**Comment by gsteckman** [comment]
You can programmatically control the pan/zoom and there was recently a [PR](https://github.com/KoalaPlot/koalaplot-core/pull/90) that added gesture support for non-Android platforms, but it hasn't been connected with a `ScrollState`.

**Comment by Feinate** [comment]
Oh Okay, thanks !
When is the new version available ? There is no GestureControl in the current 0.6.3 version.

**Comment by gsteckman** [comment]
I'll make a new release soon that includes that feature and uses the latest Compose and Kotlin versions, maybe this weekend.

**Comment by AlexZhukovich** [comment]
@gsteckman Can I set a custom zoom level? Could you share an example of a chart that is horizontally scrollable by default, with no need to zoom in first?

**Comment by gsteckman** [comment]
I don't have an example of a full chart, but with the ```LinearAxisModel``` implementations after you create it you can use ```setViewRange``` to set the current range that should be visible on the chart. So for example if your axis had a full range from 0..100, you could call ```setViewRange(0..10)``` and it would "zoom in" to show only values between 0 and 10.

**Comment by AlexZhukovich** [comment]
Thank you for your reply. Recently, I published an article about it. Maybe it will be helpful for someone who will find it here: https://alexzh.com/how-to-create-a-scrollable-chart-in-compose-multiplatform/

Full source code of scrollable list:
```kotlin
@Composable
fun DailyMoodChart(
    modifier: Modifier = Modifier,
    xData: List<Int>,
    yData: List<Float>
) {
    ChartLayout(
        modifier = modifier.padding(16.dp)
    ) {
        val xAxisModel = rememberIntLinearAxisModel(
            range = 1..xData.size,
            allowPanning = true
        ).apply { setViewRange(1..15) }
        val yAxisModel = rememberFloatLinearAxisModel(range = 0f..5f)

        XYGraph(
            xAxisModel = xAxisModel,
            yAxisModel = yAxisModel,
            panEnabled = true
        ) {
            VerticalBarPlot(
                xData = xData,
                yData = yData,
                barWidth = 0.6f,
                bar = {
                    DefaultVerticalBar(
                        brush = SolidColor(Color.Green),
                        shape = RoundedCornerShape(100)
                    )
                }
            )
        }
    }
}
```
