### ISSUE TITLE
xAxis not shown with 500 Points

### ISSUE THREAD

**Issue by timuebbing** [KoalaPlot/koalaplot-core#56]
I use the LineChartSample with a data set of 500 data points instead of the RainData set. This leads to the x-axis not being displayed correctly. If the number for the label reaches two digits, it is no longer displayed.

`@OptIn(ExperimentalKoalaPlotApi::class)
@Composable
@Suppress("MagicNumber")
private fun Chart(title: String) {
    ChartLayout(
        modifier = paddingMod,
        title = { ChartTitle(title) },
        legend = { Legend() },
        legendLocation = LegendLocation.BOTTOM
    ) {
        syncGraphList()

        XYGraph(
            xAxisModel = CategoryAxisModel(
                GraphData.labels
            ),
            yAxisModel = LinearAxisModel(
                -128f..128f,
                minimumMajorTickSpacing = 20.dp,
            ),
            xAxisStyle = rememberAxisStyle(
                color = Color.White,
                majorTickSize = 0.dp,
                minorTickSize = 0.dp,
                tickPosition = TickPosition.None,
                lineWidth = 1.dp,
                labelRotation = 0
            ),
            xAxisLabels = { AxisLabel(it, Modifier.absolutePadding(right = 2.dp)) },
            xAxisTitle = {
                Box(
                    modifier = Modifier.fillMaxWidth(),
                    contentAlignment = Alignment.BottomCenter
                ) {
                    AxisTitle("Länge [m]",
                        modifier = Modifier
                            .padding(20.dp)
                    )
                }

            },
            yAxisStyle = rememberAxisStyle(
                color = Color.White,
                majorTickSize = 0.dp,
                minorTickSize = 0.dp,
                tickPosition = TickPosition.None,
                lineWidth = 1.dp,
                labelRotation = 0
            ),
            yAxisLabels = {
                AxisLabel(it.toString(), Modifier.absolutePadding(right = 2.dp))
            },
            yAxisTitle = {
                Box(
                    modifier = Modifier.fillMaxHeight(),
                    contentAlignment = Alignment.TopStart
                ) {
                    AxisTitle(
                        "Einheit (?)",
                        modifier = Modifier.rotateVertically(VerticalRotation.COUNTER_CLOCKWISE)
                            .padding(bottom = padding)
                    )
                }

            },
            horizontalMajorGridLineStyle = KoalaPlotTheme.axis.majorGridlineStyle,
            horizontalMinorGridLineStyle = KoalaPlotTheme.axis.minorGridlineStyle,
            verticalMajorGridLineStyle = KoalaPlotTheme.axis.majorGridlineStyle,
            verticalMinorGridLineStyle = KoalaPlotTheme.axis.minorGridlineStyle,

            ) {
            GraphData.data.entries.sortedBy { it.key }.forEach { (channel, labels) ->
                var points = labels.mapIndexed { index, d ->
                    DefaultPoint(GraphData.labels[index], d.toFloat())
                }

                chart(
                    channel,
                    points,
                )
            }
        }
    }
}

@OptIn(ExperimentalKoalaPlotApi::class)
@Composable
private fun XYGraphScope<String, Float>.chart(
    channel: String,
    data: List<DefaultPoint<String, Float>>,
) {
    LinePlot(
        data = data,
        lineStyle = LineStyle(
            brush = SolidColor(colorMap[channel] ?: Color.Black),
            strokeWidth = 2.dp
        ),
        symbol = { point ->
            Symbol(
                shape = CircleShape,
                size = 2.dp,
                fillBrush = SolidColor(colorMap[channel] ?: Color.Black),
                modifier = Modifier.then(
                    Modifier.hoverableElement {
                        HoverSurface { Text(point.y.toString()) }
                    }
                )
            )
        }
    )
}`

**Comment by gsteckman** [comment]
The x-axis is using CategoryAxisModel. This model will generate 1 tick for each category and cause a corresponding x-axis tick label to be composed - will 500 of them fit in the space you have available?

**Comment by timuebbing** [comment]
They dont fit and I think that is the Problem. Is there maybe a different solution to this problem?

**Comment by gsteckman** [comment]
I suggest using one of the linear axis models with a suitable data type for your x-axis values. For example, IntLinearAxisModel if you have integers and FloatLinearAxisModel if you have real numbers (these were introduced in version 0.6.0, it looks like you are using one of the 0.5.x versions, in which case LinearAxisModel is your only option, which uses Float).

**Comment by timuebbing** [comment]
Thanks for the mention. I am now using version 0.6.0. The problem is that I need to use the CategoryAxisModel to display my data. Or is it possible to use FloatLinearAxisModel for x- and y- axis?

**Comment by gsteckman** [comment]
Yes, you can use the axis models in any combination for the x and y axes. So just change the x axis model to the float one, and then you will have more control over the major and minor ticks and their spacing. Only the major ticks will be labeled, and the minor ticks provide an additional visual guide but are optional.

**Comment by timuebbing** [comment]
oh thats perfect. Thank you very much!
