### ISSUE TITLE
scrollable XYLine chart questionaire

### ISSUE THREAD

**Issue by prabinshrestha** [KoalaPlot/koalaplot-core#62]
Hi, i have pulled the sample and check on my android device. It seems great. The rainfall data looks great.

Also I  want to know if there is any features of scrolling horizontally LineChart so when there is more data says for like 30 days. The ui may not look congested. Jan feb mar... seems congested. User will scroll horizontally and gap will be maintained to view full month.

also say if i have market price of 30 days which gives 30 data (not scrollable)
i want to show the month horizontally say jan1 jan5  feb15 feb30 (fixed) and load the plotting line in the middle for that 30 days price. Can we do this? Please provide the hint.

i mean to say  the months can load like jan,apr,sep,dec (only 4 with the gap)and all plotting will be done inbetween. 

 val months =
        listOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

// if i change months to only size of 5 it crases array out of bound.

    val rainfall = buildMap {
        put(
            "New York City",
            listOf(83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3)
        )

Also, i wonder if there is official api documentation and features. Please provide the link.

**Comment by gsteckman** [comment]
Hi, there is a pan and zoom capability on XYGraph, which works with numeric axis types but not the category axis. In the samples, the "Areas to x-axis" is one example of this. But, it only works on Android -  it appears the detectTransformGestures modifier is not providing a zoom change on desktop or web. If you want to use this with dates, you can convert the dates to a Long value, use the LongLinearAxisModel, and then in the Composable for the labels convert the Long back to a date.
