### ISSUE TITLE
Style `xAxisTitle` and `yAxisTitle` on the XYGraph

### ISSUE THREAD

**Issue by joelkanyi** [KoalaPlot/koalaplot-core#68]
First of all, thank you for this awesome Kotlin Multiplatform library.

Currently, I can only pass the `String` title, but I don't have the capability to style the text to my liking.

It would be nice if `xAxisTitle` and `yAxisTitle` could be content slots so that I can pass whatever I want, e.g.,

```Kotlin
public fun <X, Y> XYGraph(
    ...
    xAxisTitle: @Composable (() -> Unit)? = null,
    ...
    yAxisTitle: @Composable (() -> Unit)? = null,
    ...
) {
    ...
}    
```

**Comment by gsteckman** [comment]
There is an overloaded version of XYGraph that lets you do that. Around line 69 in XYGraph.kt.
