### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Monabr** [KoalaPlot/koalaplot-core#72]
Not enough documentation for the project. I'm trying to create a Bar Chart and there is absolutely no documentation for it!

**Comment by gsteckman** [comment]
> Not enough documentation for the project. I'm trying to create a Bar Chart and there is absolutely no documentation for it!

Have you had a look at the [documentation](https://koalaplot.github.io/docs/xygraphs/bar_plots/)?
