### ISSUE TITLE
Ability to disable animation

### ISSUE THREAD

**Issue by Monabr** [KoalaPlot/koalaplot-core#73]
Hello. 

I would like to be able to turn off animation for any chart. 

At the moment I am particularly interested in the bar chart.

**Comment by gsteckman** [comment]
Have you tried specifying the animationSpec, e.g., to a tween with 0 duration?

**Comment by gsteckman** [comment]
I verified that if you use `animationSpec = TweenSpec(durationMillis = 0)` then the plot won't animate.
