### ISSUE TITLE
Automatic scaling of values ​​for Y axis in bar chart

### ISSUE THREAD

**Issue by Monabr** [KoalaPlot/koalaplot-core#74]
Hello.

I would like to see automatic scaling of the values ​​for the Y axis in the bar chart. 

Why should I write this manually through the "yAxisModel" parameter? It makes no sense to me.

**Comment by gsteckman** [comment]
You can auto scale, see https://koalaplot.github.io/koalaplot-core/api/0.6.0/-koala%20-plot%20-core/io.github.koalaplot.core.xygraph/auto-scale-range.html and the documentation on setting the range [here](https://koalaplot.github.io/docs/xygraphs/).

If you don't like the algorithm it uses, then the api lets you implement your own, which is more flexible than a library that implements something you have no control over to replace.
