### ISSUE TITLE
Way to avoid too dense values in CategoryAxisModel

### ISSUE THREAD

**Issue by naixx** [KoalaPlot/koalaplot-core#76]
![image](https://github.com/user-attachments/assets/7c5d0953-97bf-4fc9-b9f4-f3602d99e9e1)

Is it possible to skip some labels and ticks when there are many x-axis values?

The way I'm constructing it is pretty simple, but I don't see an option to skip. Not sure if minimumMajorTickSpacing is doint anything at all

```
    XYGraph(
        xAxisModel = CategoryAxisModel(
            xCategories
        ),
        yAxisModel = IntLinearAxisModel(
            yValues,
      
        )
```

**Comment by gsteckman** [comment]
The CategoryAxisModel doesn't use the minimumMajorTickSpacing value. This can probably be removed from the AxisModel interface it implements, and will help avoid confusion. 

For this type of an axis, there are some uncertainties as to what the "best" behavior should be. Should ticks be skipped and their values, or only the ticks? Should ticks and values be kept but labels skipped? Something else? If the labels and ticks are skipped then how does the user of the plot know what the values represent? This creates a usability issue.

If you have any pointers to other plotting libraries that take some actions like this and what they do and when, I can take a look at it and consider it.

As an alternative, you can rotate the x-axis labels by some amount, e.g. 90-degrees.

**Comment by naixx** [comment]
@gsteckman ok, I think, there could be a workaround. However I get another issue with dense values. Chart width is measured differently, I specifically painted plot in a vibrant color. Any ideas how to fix that?

![image](https://github.com/user-attachments/assets/33a38c2a-826e-493a-a88a-26d01d36488f)

**Comment by gsteckman** [comment]
That looks like a bug that I thought I fixed previously.  What version are you using?

**Comment by naixx** [comment]
0.6.2

**Comment by gsteckman** [comment]
This is fixed now in 0.6.3.

**Comment by naixx** [comment]
![image](https://github.com/user-attachments/assets/831d9ff3-377d-4959-b541-0822aa52d333)
Thats probably another issue. To simulate dense items on the x axis, I duplicated initial data like `list+list`. And got this result.

Original issue seems to be fixed

**Comment by gsteckman** [comment]
You can't have duplicate items per `equals()` in a Category axis. Think of it this way: if I have a category called "Cats", and a 2nd category called "Cats", and then I want to plot the value 5 for a category of "Cats", where should it go?

I could have the CategoryAxis throw an exception on creation (maybe an IllegalArgumentException) if there are any duplicate values in the list of Categories provided to the constructor. At least that would be immediate and clear that there is a usage violation.
