### ISSUE TITLE
Can XYGraph handle missing y values?

### ISSUE THREAD

**Issue by MrJohn10** [KoalaPlot/koalaplot-core#87]
I want to create a graph that visualizes users' weights over time, where each point on the graph corresponds to a recorded weight for a specific date. If no weight is recorded for a particular date, the graph should still include an X-axis point for that date but with no corresponding Y value.

Despite missing Y values, I would like the line connecting the existing data points to remain continuous, ideally with a smooth or rounded appearance between the points.

Is it possible to achieve using the XYGraph?
I have the list of points <Int, Long?>, but when creating LinePlot data i don't see the way to generate an empty point.

```            
LinePlot(
    data = graphData.points.mapIndexed { index, point ->
        Point(index, point.y?:-1L)
    }
```

**Comment by gsteckman** [comment]
LinePlot takes a list of X, Y data points to plot. If there is no data point, then leave it out of the list of data passed to the LinePlot.

If you specify a line type, LinePlot will connect all points. If you want discontinuous lines this can be done with separate LinePlots for each continuous line you want to plot.

Currently there is only support for straight lines connecting each point or a "stair step" type of line. Using a Bezier curve to connect points would be a new feature.

**Comment by MrJohn10** [comment]
Thanks, turns out I was filtering the points in the wrong way. This code works:
```                
LinePlot(
    modifier = Modifier.height(200.dp),
    data = graphData.points.mapIndexedNotNull { index, point ->
        point.y?.let { y -> Point(index, y) }
    }
```
