### ISSUE TITLE
Allow for customizing text style

### ISSUE THREAD

**Issue by Vichy97** [KoalaPlot/koalaplot-core#89]
I'm using an XYGraph and for the most part, the text style is fine because it matches the material theming, but I would like to force labels to be single-line. In my case labels are only 2-4 characters and sometimes the last label gets wrapped and it looks very bad. Allowing label customization would be great and should be fairly straight forward to implement

**Comment by gsteckman** [comment]
Labels can be any `Composable` - see [here](https://koalaplot.github.io/koalaplot-core/api/0.6.2/-koala%20-plot%20-core/io.github.koalaplot.core.xygraph/-x-y-graph.html). There is also an `XYGraph` overload that takes String for labels, which is probably what you are using, but if you want to customize the label you should use the version that uses Composables..
