### ISSUE TITLE
Invert Y Axis of XYGraph

### ISSUE THREAD

**Issue by chrishopkin** [KoalaPlot/koalaplot-core#96]
Hi, thank you for creating this library, it's looking great!

Would it be possible to invert the Y Axis such that the values are descending rather than ascending? LinearAxisModel enforces the range to be ascending (range.last > range.first), but if there were an option to invert the axes on XYGraph, that would be great.

Thank you

Chris

**Comment by gsteckman** [comment]
So the smallest value would be at the top of the graph, and values increase as you go down?

**Comment by chrishopkin** [comment]
Yes that's right. Here's an example from Strava which plots pace on the Y axis where the slowest pace is at the bottom (largest value) and the quickest at the top (smallest value).

![Screenshot_20241208-233416](https://github.com/user-attachments/assets/78003992-48cb-4307-89f3-272dc0166112)

**Comment by OlliZi** [comment]
Maybe you can invert the y-axis yourself?

yAxisLabels = { (graph.size - it.toInt()).toString() },

**Comment by gsteckman** [comment]
That won't work because the axis also transforms the plot coordinates to a distance along the axis and that will need to be inverted as well. But, it doesn't look complicated and I'll take a look at it.

**Comment by gsteckman** [comment]
I pushed this change on the Main branch. Check it out!

**Comment by chrishopkin** [comment]
Great, thanks @gsteckman, I will give it a go as soon as I can!

**Comment by chrishopkin** [comment]
@gsteckman - I've just tried this out and it's working great! Thank you for getting this in so quickly 👍
